/*
 * generated by Xtext
 */
package com.tocea.scertify.architecture.xadl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ArchitectureDSLUiModule extends com.tocea.scertify.architecture.xadl.ui.AbstractArchitectureDSLUiModule {
	public ArchitectureDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
