/*
* generated by Xtext
*/
package com.tocea.scertify.architecture.xadl.ui.contentassist;

import com.tocea.scertify.architecture.xadl.ui.contentassist.AbstractArchitectureDSLProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ArchitectureDSLProposalProvider extends AbstractArchitectureDSLProposalProvider {

}
