/*
 * generated by Xtext
 */
package com.tocea.scertify.architecture.xadl;

import org.eclipse.xtext.generator.IGenerator;
import org.eclipse.xtext.scoping.IScopeProvider;

import com.tocea.scertify.architecture.xadl.generator.ExtensibleArchitectureGenerator;
import com.tocea.scertify.architecture.xadl.scoping.ArchitectureDSLScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ArchitectureDSLRuntimeModule extends com.tocea.scertify.architecture.xadl.AbstractArchitectureDSLRuntimeModule {
    
	@Override
	public Class<? extends IScopeProvider> bindIScopeProvider() {
		return ArchitectureDSLScopeProvider.class;
	}

	@Override
	public Class<? extends IGenerator> bindIGenerator() {
		return ExtensibleArchitectureGenerator.class;
	}

}
