/*
 * generated by Xtext
 */
package com.tocea.codewatch.architecture.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ArchitectureDSLUiModule extends com.tocea.codewatch.architecture.dsl.ui.AbstractArchitectureDSLUiModule {
	public ArchitectureDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
