/*
* generated by Xtext
*/
package com.tocea.codewatch.architecture.query.dsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.tocea.codewatch.architecture.query.dsl.services.QueryDslGrammarAccess;

public class QueryDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private QueryDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.tocea.codewatch.architecture.query.dsl.parser.antlr.internal.InternalQueryDslParser createParser(XtextTokenStream stream) {
		return new com.tocea.codewatch.architecture.query.dsl.parser.antlr.internal.InternalQueryDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Queries";
	}
	
	public QueryDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(QueryDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
