/*
* generated by Xtext
*/
package com.tocea.codewatch.architecture.query.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class QueryDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("com/tocea/codewatch/architecture/query/dsl/parser/antlr/internal/InternalQueryDsl.tokens");
	}
}
