/*
* generated by Xtext
*/
package com.tocea.codewatch.architecture.dsl.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class ArchitectureDSLOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
