/*
* generated by Xtext
*/
package com.tocea.codewatch.architecture.dsl.ui.contentassist;

import com.tocea.codewatch.architecture.dsl.ui.contentassist.AbstractArchitectureDSLProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ArchitectureDSLProposalProvider extends AbstractArchitectureDSLProposalProvider {

}
