/*
* generated by Xtext
*/
package com.tocea.scertify.architecture.xadl.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class ArchitectureDSLOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
