/*
 * generated by Xtext
 */
package com.tocea.codewatch.architecture.query.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class QueryDslUiModule extends com.tocea.codewatch.architecture.query.dsl.ui.AbstractQueryDslUiModule {
	public QueryDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
