/*
* generated by Xtext
*/
package com.tocea.codewatch.architecture.query.dsl.ui.contentassist;

import com.tocea.codewatch.architecture.query.dsl.ui.contentassist.AbstractQueryDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class QueryDslProposalProvider extends AbstractQueryDslProposalProvider {

}
