/*
* generated by Xtext
*/
package com.tocea.codewatch.architecture.query.dsl.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

import com.tocea.codewatch.architecture.query.dsl.queryDsl.Query;

/**
 * customization of the default outline structure
 * 
 */
public class QueryDslOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
	boolean _isLeaf(Query q){
		return true;
	}
}
